### PR TITLE
Impl debug trait for ErrorDetail

### PR DESCRIPTION
**Pull request by outofxxx**
Fixes P-161

RequestVC failed logs as below:

```
received one error: Ok("Failed to build assertion due to: RequestVCFailed(BnbDigitDomainClub(Bnb999ClubMember), DataProviderError(BoundedVec([78, 111, 100, 101, 114, 101, 97, 108, 69, 114, 114, 111, 114, 40, 34, 78, 111, 100, 101, 114, 101, 97, 108, 32, 114, 101, 115, 112, 111, 110, 115, 101, 32, 101, 114, 114, 111, 114, 58, 32, 69, 114, 114, 111, 114, 58, 32, 73, 79, 32, 101, 114, 114, 111, 114, 34, 41], 100)))")
```

Display the `ErrorDetail` message in string instead of bytes array.

### CODE REVIEW

**Review by jonalvarezz — APPROVED** [review]
Thanks! a small but important one.

It'd be great if you could put an example of how it looks like now.

**Comment by zhouhuitian** [comment]
Related issue: https://linear.app/litentry/issue/P-161/display-the-error-in-readable-string-in-logs

**Comment by Kailai-Wang** [comment]
> It'd be great if you could put an example of how it looks like now.

Yes it would be great

**Comment by outofxxx** [comment]
An example from this [thread](https://litentry.slack.com/archives/C064L4R4ENN/p1711058628219699?thread_ts=1711058591.490209&cid=C064L4R4ENN):

Before : 
```
received one error: Ok("Failed to build assertion due to: RequestVCFailed(VIP3MembershipCard(Gold), DataProviderError(BoundedVec([82, 101, 113, 117, 101, 115, 116, 69, 114, 114, 111, 114, 40, 34, 72, 116, 116, 112, 82, 101, 113, 69, 114, 114, 111, 114, 40, 73, 79, 40, 79, 115, 32, 123, 32, 99, 111, 100, 101, 58, 32, 49, 49, 49, 44, 32, 107, 105, 110, 100, 58, 32, 67, 111, 110, 110, 101, 99, 116, 105, 111, 110, 82, 101, 102, 117, 115, 101, 100, 44, 32, 109, 101, 115, 115, 97, 103, 101, 58, 32, 92, 34, 85, 110, 107, 110, 111, 119, 110, 32, 101, 114, 114, 111, 114, 58, 32, 49, 49, 49], 100)))")
```

After:
`DataProviderError(RequestError("HttpReqError(IO(Os { code: 111, kind: ConnectionRefused, message: \"Unknown error: 111)`

**Pull request merged**
