### PR TITLE
add trusted cli nonce command test

### PR DESCRIPTION
**Pull request by kziemianek**
Adds check to see if trusted cli command `nonce` works.

relates: #1851

### CODE REVIEW

**Comment by Kailai-Wang** [comment]
I feel like having a dedicated nonce script is a bit overkill, the `nonce == 0` test case doesn't bring a lot either as that's the default value.

Can we reuse some existing test cases to do it?
E.g. `demo_shielding_unshielding.sh` where we have nonce retrieval too, but through `getStorage`. Maybe we can make adjustments there?

**Comment by Kailai-Wang** [comment]
Actually it is not necessarily related to #1851, that issue seems more like a bug in implementation :(

**Comment by kziemianek** [comment]
> I feel like having a dedicated nonce script is a bit overkill, the `nonce == 0` test case doesn't bring a lot either as that's the default value.

The idea behind this test is to verify whether the command is working as expected with real node, not to check nonce default value 🙃 . We can change assertion but this one seemed most straightforward to me.

**Comment by kziemianek** [comment]
This should be implicitly verified by https://github.com/litentry/litentry-parachain/pull/1848/files#diff-a79aa284ab66e6a189272e6ecd6c428f9f179792e6835691992128dfdcb19e69R104 too, so if you feel like this script is an overkill, we can close this. Another check like this will also extend CI check by next ~10 min which we probably want to avoid.

**Comment by Kailai-Wang** [comment]
> This should be implicitly verified by https://github.com/litentry/litentry-parachain/pull/1848/files#diff-a79aa284ab66e6a189272e6ecd6c428f9f179792e6835691992128dfdcb19e69R104 too, so if you feel like this script is an overkill, we can close this. Another check like this will also extend CI check by next ~10 min which we probably want to avoid.

Yes I'll prefer that (including it when testing other functionalities)
Partially because the setup effort to even test one such simple RPC is not trivial 😂 

Btw the `polling` in that script might be still needed, in our experience, the live query can easily fail as it's too early for the state to change.

**Pull request closed without merging**
