### PR TITLE
Add remove_vault in pallet-bitacross

### PR DESCRIPTION
**Pull request by Kailai-Wang**
### Context

As topic. It adds `remove_vault` to remove unneeded vaults in the pallet

### CODE REVIEW

**Review by BillyWooo — APPROVED** [review]
👍

**Review by kziemianek — CHANGES_REQUESTED** [review]
If any keys are removed from vault we should remove them from bitacross-workers aswell through event handler.

**Comment by Kailai-Wang** [comment]
> If any keys are removed from vault we should remove them from bitacross-workers aswell through event handler.

This is a good point - what how should this be handled exactly?
Is this registry used by the client only or by workers too?

**Comment by Kailai-Wang** [comment]
As discussed, let's firstly make sure that we have some way to remove unneeded entries in the vault, then we'll take a deeper look how we shall improve the on-chain and worker logic

**Review by kziemianek — APPROVED** [review]

**Pull request merged**
