### PR TITLE
Hotfix lit token address

### PR DESCRIPTION
**Pull request by outofxxx**
as title.

### CODE REVIEW

**Review by arieljbirnbaum — APPROVED** [review]
:ship:

**Review by kziemianek — APPROVED** [review]
it shouldn't be case sensitive.

If this is specific to achainable we should remain address unchanged and use `to_lowercase` to prevent such problems in the future.

**Comment by kziemianek** [comment]
Do we need fix on `dev` as well ?

**Comment by arieljbirnbaum** [comment]
@kziemianek the change is included in #1986 which targets `dev`

**Pull request merged**
