### PR TITLE
local dev env config

### PR DESCRIPTION
**Pull request by kziemianek**
For dev purposes `tee-worker` should be integrating with mock services.
Currently if we start local dev env without any config changes ts-test won't pass.

We overlooked this change in one of recent PR.

### CODE REVIEW

**Review by Kailai-Wang — APPROVED** [review]
Indeed

cc @BillyWooo in case you see any problem

**Comment by Kailai-Wang** [comment]
Btw I notice we have different file structures between bitacross and normal worker: `tee-worker/local-setup/.env.dev` vs `bitacross-worker/.env.dev`

**Comment by kziemianek** [comment]
Yes, I started working on bitacross before #2417 was merged so few changes may be missing.

**Comment by BillyWooo** [comment]
> Indeed
> 
> cc @BillyWooo in case you see any problem

No problem. We discussed together. 😄

**Pull request merged**
