### PR TITLE
hardcode data provider config into prod enclave

### PR DESCRIPTION
**Pull request by kziemianek**
- Removes `running-mode` CLI arg
- Hardcodes data provider config for prod env
- Adds reading secrets from env variables
- Adds possibility for overriding data provider config by env variables on non prod env
- Decouples data providers from global config variable (configs are provided as constructor parameters)
- `StfTaskContext` holds reference to `ShieldingKeyRepository` because shielding key can be changed after mu-ra key provisioning.

### CODE REVIEW

**Comment by BillyWooo** [comment]
In general, the refactor looks good for me. Let's get the CI tests pass.
Two concerns:
1. how does this refactor affect the mock server?
2. I would suggest to wait for [PRs](https://github.com/litentry/litentry-parachain/pull/2288) from @zhouhuitian and @higherordertech and merge after theirs PRs merged. Because this refactor will block their deployment to current `staging` env.

**Comment by kziemianek** [comment]
@BillyWooo this PR doesn't affect mock server. Regarding waiting for other PRs im fine with it. We can wait even longer - untill we drop `staging` branch.

**Review by Kailai-Wang — APPROVED** [review]
Looks good, thanks!

**Comment by BillyWooo** [comment]
> untill we drop staging branch.

I would say so. Thanks

**Comment by 0xverin** [comment]
> @BillyWooo this PR doesn't affect mock server. Regarding waiting for other PRs im fine with it. We can wait even longer - untill we drop `staging` branch.

Will we affect the mock server in the future?

**Comment by kziemianek** [comment]
> > @BillyWooo this PR doesn't affect mock server. Regarding waiting for other PRs im fine with it. We can wait even longer - untill we drop `staging` branch.
> 
> Will we affect the mock server in the future?

I think we don't have any plans for it.
We can adjust mocks logic to fit our testing needs.

**Comment by kziemianek** [comment]
I've made few changes, there very plenty of conflicts and problem with shielding key so I'm requesting a review again 🙃

**Review by BillyWooo — COMMENTED** [review]
in general, LGTM. Some points to talk with you privately.

**Review by BillyWooo — APPROVED** [review]
Please resolve the conflict and get CI jobs pass. Thank you.

**Pull request merged**
