### PR TITLE
fix: P-854 change precondition of BNB domain VC value being true

### PR DESCRIPTION
**Pull request by wli-pro**
to require amount to be greater than 0

### Labels

Please apply following PR-related labels when appropriate:
- `C0-breaking`: if your change could break the existing client, e.g. API change, critical logic change 
- `C1-noteworthy`: if your change is non-breaking, but is still worth noticing for the client, e.g. reference code improvement

### Testing Evidences

Please attach any relevant evidences if applicable

### CODE REVIEW

**Review by Kailai-Wang — APPROVED** [review]
Thanks!

So it means even if `amount` is 0, the `value` was `true` based on the previous impl?

**Comment by Kailai-Wang** [comment]
But this is not strictly related to P-854, is it?

In that issue, the user has **1** bnbDomain but VC says "not qualified".

**Comment by wli-pro** [comment]
> `value` was `true` based on the previous impl?

Yes, which was wrong

**Comment by wli-pro** [comment]
> But this is not strictly related to P-854, is it?
> 
> In that issue, the user has **1** bnbDomain but VC says "not qualified".

Actully this reported user has 1 but expired domain, hence the VC should really return false only.

**Pull request merged**
