### PR TITLE
change vc proof signature message

### PR DESCRIPTION
**Pull request by kziemianek**
Change a message to sign from VC's json to mrenclave value in order to create vc's proof signature

relates: #1861

### CODE REVIEW

**Comment by outofxxx** [comment]
Changing to mrenclave does not reduce the size of the VC, and if issue. mrenclave is used, then if the signatures of all VC generated by the same worker are the same

**Comment by kziemianek** [comment]
> Changing to mrenclave does not reduce the size of the VC, and if issue. mrenclave is used, then if the signatures of all VC generated by the same worker are the same

Hi, what are your concerns ?
VCs can still be only generated by registered enclaves and submitted to parachain vc registry only by them. There was an discussion [here](https://www.notion.so/web3builders/Review-VC-fields-d7132757fcdc4554b53b1f4ab93ab507)

**Review by Kailai-Wang — APPROVED** [review]
Looks good to me :)

**Comment by kziemianek** [comment]
Merging it. @zhouhuitian if you have any concerns or doubts we can discuss suggested changes again.

**Pull request merged**
