### PR TITLE
debug: change staking parameter

### LINKED ISSUE #921: Finalise the parameters in `parachainStaking`
Especially the following parameters, are they still up-to-date?

```
	pub const MinCollatorStk: Balance = 50 * DOLLARS;
	pub const MinCandidateStk: Balance = 50 * DOLLARS;
	pub const MinDelegation: Balance = 50 * DOLLARS;
	pub const MinDelegatorStk: Balance = 50 * DOLLARS;
```

### PR DESCRIPTION
**Pull request by wangminqi**
This closes #921

### CODE REVIEW

**Comment by wangminqi** [comment]
Please do not merge this branch until staking is officially online for the community.

**Comment by Kailai-Wang** [comment]
@wangminqi can you please bump the version too? like 9110 -> 9115 for litentry?

We'll perform a runtime upgrade soon.

**Comment by wangminqi** [comment]
I have added the version bump for both rococo and litentry.

**Review by Kailai-Wang — APPROVED** [review]
Looks good, thanks

**Comment by jingleizhang** [comment]
LGTM

**Pull request merged**
