### PR TITLE
Fix assertion identifiers missing the `$` prefix

### PR DESCRIPTION
**Pull request by outofxxx**
as topic.

**Notice that such fix needs a sync release with the client's vc-sdk  package to continuing supporting both the previous and the new claim key.**

### CODE REVIEW

**Review by Kailai-Wang — APPROVED** [review]
Thank you!

cc @jonalvarezz

**Review by jonalvarezz — APPROVED** [review]
> Notice that such fix needs a sync release with the client's vc-sdk package to continuing supporting both the previous and the new claim key.

Could you please create the follow-up ticket and put it on the backlog?

**Comment by BillyWooo** [comment]
@jonalvarezz do we need any update from sdk point of view?

**Comment by jonalvarezz** [comment]
yes totally, as well as duplicate JSON Schemas so that both versions are valid. The price of the rush 😄

**Review by kziemianek — COMMENTED** [review]
Is it mandatory for assertion item to be prefixed with `$` ? 
If yes can we add such check and fail if condition is not met ?

It's always good to express such rules in code.

**Comment by jonalvarezz** [comment]
> Is it mandatory for assertion item to be prefixed with `$` ? If yes can we add such check and fail if condition is not met ?
> 
> It's always good to express such rules in code.

I second the lint checks to enforce consitency 👍

**Pull request merged**
