### PR TITLE
Fix `production` feature propagation

### PR DESCRIPTION
**Pull request by Kailai-Wang**
### Context

It's not a flawless PR due to time limit. I only make sure critical part is covered.

To solve it perfectly we need to add the feature propagation in each intermediate crate (including the **node/runtime**), and/or have a smarter way to deal with the conditional compilation.

### CODE REVIEW

**Comment by kziemianek** [comment]
Compilation doesn't fail if I put this 

```
match assertion {
			// the signer will be checked inside A13, as we don't seem to have access to ocall_api here
			Assertion::A13(_) => (),
			_ => if_production_or!(
				compile_error!("This macro should fail"),
				ensure!(
					ensure_self(&signer, &who) || ensure_alice(&signer_account),
					"Unauthorized signer",
				)
			),
		}
```

in `litentry-parachain/tee-worker/litentry/core/vc-issuance/lc-vc-task-receiver/src/lib.rs` - which indicates that production feature was not applied.
Compilation fails if I add this `compile_error` macro invocation to `getter.rs`

Command:
```
make SGX_MODE=SW
```

Do you know why ?

**Comment by Kailai-Wang** [comment]
You didn't compile with `SGX_PRODUCTION=1`, so no production feature, thus no compile error - guess that's expected?

**Review by kziemianek — APPROVED** [review]
Looks ok, thanks.
Checked if it works using `compile_error` macro.

**Comment by kziemianek** [comment]
> You didn't compile with `SGX_PRODUCTION=1`, so no production feature, thus no compile error - guess that's expected?

Yes, I was experimenting with modified `Makefile` and added `production` feature to `WORKER_FEATURES` . I forgot about this compilation option.

**Review by BillyWooo — APPROVED** [review]
👍

**Pull request merged**
