### PR TITLE
702 update to polkadot v0.9.26

### PR DESCRIPTION
**Pull request by BISHOy2580**
Can you send for me after finsh
In trast walled bnb smart chin 
version                      : 9080
size                         : 748459
rustc                        : rustc 1.62.0 (a8314ef7d 2022-06-27)
sha256                       : 0xf54550626a75c8a6fe7574727d9b499e01e5486ec8a38403d19068de7f19c7c9
blake2-256                   : 0xd5e31f0b16c3932abd5aac67c5189aceee050588ba2f4dada21df8d8b2980555
proposal (setCode)           : 0x9045f69ebb6a704d50a2103d7a9c1d9d2f540b11051187ff23a39123ca4f36d3
proposal (authorizeUpgrade)  : 0x3a99fd7e4d1d344af706c3dbe70d34e6b3ebd62b47a6241d5e2666e42801dd3b
Inthe trast walled bnb smart chin

0xc805f3D4b190Ca2C6Add8cDAC3f309C142Bad622

### CODE REVIEW

**Comment by BISHOy2580** [comment]
Ok cancel

**Comment by BISHOy2580** [comment]
https://github.com/litentry/litentry-parachain/pull/713#issuecomment-1189764328

**Comment by BISHOy2580** [comment]
Cansel plu re

**Comment by Kailai-Wang** [comment]
No more spam please.
As mentioned in another thread, if you have any specific needs, please join the discord channel and ask there, our admins will follow up on it.

**Pull request closed without merging**
