### PR TITLE
Use `skip_filtering` when getting eligible identities

### PR DESCRIPTION
**Pull request by Kailai-Wang**
### Context

It should be a better way than `force_retain_web2_identities`.

It's used as a parameter in `get_eligible_identities` to decide if we should simply pass those identities through and let assertion logic handle them.

### CODE REVIEW

**Review by wli-pro — APPROVED** [review]
LGTM

**Comment by kziemianek** [comment]
Does this mean once we migrate all assertions to dynamic assertions we will remove `desired_web3networks` ?

**Comment by Kailai-Wang** [comment]
> Does this mean once we migrate all assertions to dynamic assertions we will remove `desired_web3networks` ?

Yes if we decide to remove all code of legacy assertions

**Comment by kziemianek** [comment]
This looks like a noteworthy change because it has impact on dynamic assertion results.

**Review by kziemianek — APPROVED** [review]

**Pull request merged**
