### PR TITLE
Decrease ceremony runner tick interval to 1 ms

### PR DESCRIPTION
**Pull request by kziemianek**
* Decreases ceremony runner tick interval to 1 ms

### CODE REVIEW

**Comment by Kailai-Wang** [comment]
Have you tried it locally how long it takes now? Or do we wait for deployment with this commit?

**Comment by kziemianek** [comment]
It decreased from 2.7 s to 20 ms but times vary depends on run (network calls).

Previously: Ceremony took: 2.699441812s
Now: Ceremony took: 20.217815ms

**Review by BillyWooo — APPROVED** [review]
Nice.

**Comment by BillyWooo** [comment]
Just an idea comes to my mind: according to your test, if we adjust the tick to e.g. 5ms, would it increase the efficiency?  @kziemianek

**Pull request merged**
