### PR TITLE
testing the auto label code

### PR DESCRIPTION
**Pull request by niteshb3495**

### CODE REVIEW

**Review by Kailai-Wang — CHANGES_REQUESTED** [review]
Testing request changes

**Comment by Kailai-Wang** [comment]
Hmm.. I changed it to "changes requested", but it seems the tags are not updated accordingly

Apart from that, I have a few more comments:
- shall we consider the status change between `draft` and `ready to review` and add/remove labels accordingly?
- shall we restrict the autolabeling only to some branch? Like only listen to PRs to `dev` branch
- I think it might be possible for you to test it (without my interaction) by creating a sub-branch of `249-refine-auto-labeling` to open a PR to your `249-..` branch from there

**Comment by Kailai-Wang** [comment]
Too stale, close it for now.

**Comment by RieserStern** [comment]
I'm interested your project as a blockchain developer

**Comment by Kailai-Wang** [comment]
> I'm interested your project as a blockchain developer

Hi @RieserStern , thanks for your interest.

Could you please directly apply it via https://litentry.com/careers? Or if you have done that already, I'm sure our personnel and engineering colleagues will look into it.

**Pull request closed without merging**
