### PR TITLE
feat: P-947 add solidity DarenMarket platform user vc

### PR DESCRIPTION
**Pull request by wli-pro**
### Labels

Please apply following PR-related labels when appropriate:
- `C0-breaking`: if your change could break the existing client, e.g. API change, critical logic change 
- `C1-noteworthy`: if your change is non-breaking, but is still worth noticing for the client, e.g. reference code improvement

### Testing Evidences

Please attach any relevant evidences if applicable

only find false wallet address so only false result is given:
```
./bin/litentry-cli trusted -d request-vc did:litentry:evm:0x2136184d88f0e711f59098586511e60005404db8 -a "dynamic 0000000000000000000000000000000000000001 0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000b446172656e4d61726b6574000000000000000000000000000000000000000000"
>>> identity: Evm(Address20)
>>> nonce: 0
>>> assertions: [Dynamic(DynamicParams { smart_contract_id: 0x0000000000000000000000000000000000000001, smart_contract_params: Some(BoundedVec([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 68, 97, 114, 101, 110, 77, 97, 114, 107, 101, 116, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 1024)), return_log: false })]
----Generated VC-----
{"@context":["https://www.w3.org/2018/credentials/v1","https://w3id.org/security/suites/ed25519-2020/v1"],"id":"0x9449ee3bfc543c2b3e2807e01a77e0239fa27127f86e581204302a5f00ae0ea8","type":["VerifiableCredential"],"credentialSubject":{"id":"did:litentry:evm:0x2136184d88f0e711f59098586511e60005404db8","description":"You are a user of a certain platform","type":"Platform user","assertionText":"","assertions":[{"and":[{"src":"$platform","op":"==","dst":"DarenMarket"}]}],"values":[false],"endpoint":"http://localhost:9933/"},"issuer":{"id":"did:litentry:substrate:0x0b9df679f406a51a2e53b87d8e3fc86e792e277fe932d9535b40692bec9e3789","name":"Litentry TEE Worker","mrenclave":"BqTLDoc1v72gTCVh6AGi3KEGphUFixf6naa9RwKszuxW","runtimeVersion":{"parachain":9191,"sidechain":109}},"issuanceDate":"2024-08-08T23:49:31.934630623+00:00","parachainBlockNumber":116,"sidechainBlockNumber":224,"proof":{"created":"2024-08-08T23:49:31.934976376+00:00","type":"Ed25519Signature2020","proofPurpose":"assertionMethod","proofValue":"bb62fe50261132131bf668ab63b7f52bfe402b92ffa0bbebba43fc524afc756893e3da6afe8340cd0d52e181e2378b320b35b7ad59f38485448f3c9f6581b500","verificationMethod":"0x44da3459814cb003846aece78984e0d064f6b7c1b4c3e4c7bf03b598ea550ba4"},"credentialSchema":{"id":"https://raw.githubusercontent.com/litentry/vc-jsonschema/main/dist/schemas/24-platform-user/1-1-2.json","type":"JsonSchemaValidator2018"}}
```

### CODE REVIEW

**Review by 0xverin — COMMENTED** [review]
Overall looks fine, but I have a question. Are the tests for hardhat not running in the CI? I didn't see any relevant CI tests. Did I see it wrong?

**Comment by higherordertech** [comment]
> Overall looks fine, but I have a question. Are the tests for hardhat not running in the CI? I didn't see any relevant CI tests. Did I see it wrong?

It's here: https://github.com/litentry/litentry-parachain/pull/2927/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03f

**Review by BillyWooo — COMMENTED** [review]
LGTM.

**Comment by wli-pro** [comment]
> Details

Well spot, added the test step in CI too now: https://github.com/litentry/litentry-parachain/actions/runs/10346981274/job/28636423866?pr=2978

**Review by kziemianek — APPROVED** [review]

**Pull request merged**
