### PR TITLE
Add bean support for TokenAmountHolding VC

### PR DESCRIPTION
**Pull request by wli-pro**
…nt VC

### Labels

Please apply following PR-related labels when appropriate:
- `C0-breaking`: if your change could break the existing client, e.g. API change, critical logic change 
- `C1-noteworthy`: if your change is non-breaking, but is still worth noticing for the client, e.g. reference code improvement

### Testing Evidences

Please attach any relevant evidences if applicable

### CODE REVIEW

**Review by Kailai-Wang — APPROVED** [review]
Looks good from my side, if we want to add COMBO we probably need to add another a separete `bean_balance`

**Comment by Kailai-Wang** [comment]
And yes I can see how urgent it was 😂 

image

**Review by felixfaisal — APPROVED** [review]
Thanks @higherordertech ! Looks good 
So i was tracking the logic, 

To use `NodeReal` for COMBO we have to make changes to https://github.com/litentry/litentry-parachain/blob/7e45fbd994d06ad4f716c0fd3ac09e8d26c07f86/tee-worker/litentry/core/data-providers/src/nodereal_jsonrpc.rs#L67 
and rest of the things in this file. 

So we need to do the above changes for supporting COMBO.

**Comment by Kailai-Wang** [comment]
Attaching test evidence too:

```
./litentry-cli trusted -d request-vc did:litentry:evm:0x50bdf51209BABDd7a86a98AB80E824604Cec452a -a "token-holding-amount bean"
```

Example generated VC:
```
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/security/suites/ed25519-2020/v1"
  ],
  "id": "0x79452104b10ec5a35ba0f77a4a6fdf0c1f7d5bf9b5418e09ea5b4c6da17f32fa",
  "type": [
    "VerifiableCredential"
  ],
  "credentialSubject": {
    "id": "did:litentry:evm:0x50bdf51209babdd7a86a98ab80e824604cec452a",
    "description": "The amount of a particular token you are holding",
    "type": "Token Holding Amount",
    "assertionText": "TokenHoldingAmount(Bean)",
    "assertions": [
      {
        "and": [
          {
            "src": "",
            "op": "==",
            "dst": "BEAN"
          },
          {
            "or": [
              {
                "and": [
                  {
                    "src": "",
                    "op": "==",
                    "dst": "bsc"
                  },
                  {
                    "src": "",
                    "op": "==",
                    "dst": "0x07da81e9a684ab87fad7206b3bc8d0866f48cc7c"
                  }
                ]
              },
              {
                "and": [
                  {
                    "src": "",
                    "op": "==",
                    "dst": "combo"
                  },
                  {
                    "src": "",
                    "op": "==",
                    "dst": "0xba7b9936a965fac23bb7a8190364fa60622b3cff"
                  }
                ]
              }
            ]
          },
          {
            "src": "",
            "op": ">=",
            "dst": "0"
          },
          {
            "src": "",
            "op": "<",
            "dst": "1500"
          }
        ]
      }
    ],
    "values": [
      true
    ],
    "endpoint": "http://localhost:9933"
  },
  "issuer": {
    "id": "did:litentry:substrate:0xda340fed8f85f3a3ee9dd2c7aa36c29c79ad87eb19b5d78544278d7605566caf",
    "name": "Litentry TEE Worker",
    "mrenclave": "8GkkAQ81Rc9TrRn6JWtUwEZD8DWF5k8DbLBxroX5Ln1N",
    "runtimeVersion": {
      "parachain": 9180,
      "sidechain": 106
    }
  },
  "issuanceDate": "2024-05-29T23:02:45.856569183+00:00",
  "parachainBlockNumber": 9,
  "sidechainBlockNumber": 10,
  "proof": {
    "created": "2024-05-29T23:02:45.856827055+00:00",
    "type": "Ed25519Signature2020",
    "proofPurpose": "assertionMethod",
    "proofValue": "4465a6a2f8b763888cf1f123afb8cb2e7b6d224f3b1fc17f3ea5796127754f5cf74e0e11511e12e75611ce5a2408eef2fe1f6f1fded3995d825b7e35c2b66804",
    "verificationMethod": "0xda340fed8f85f3a3ee9dd2c7aa36c29c79ad87eb19b5d78544278d7605566caf"
  },
  "credentialSchema": {
    "id": "https://raw.githubusercontent.com/litentry/vc-jsonschema/main/dist/schemas/25-token-holding-amount/1-1-2.json",
    "type": "JsonSchemaValidator2018"
  }
}
```

**Comment by Kailai-Wang** [comment]
With real endpoint:

```
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/security/suites/ed25519-2020/v1"
  ],
  "id": "0x6f25985d2b9230c41bca28f349da19b26c0347870a405d7eb52df46fcc8652da",
  "type": [
    "VerifiableCredential"
  ],
  "credentialSubject": {
    "id": "did:litentry:evm:0x50bdf51209babdd7a86a98ab80e824604cec452a",
    "description": "The amount of a particular token you are holding",
    "type": "Token Holding Amount",
    "assertionText": "TokenHoldingAmount(Bean)",
    "assertions": [
      {
        "and": [
          {
            "src": "",
            "op": "==",
            "dst": "BEAN"
          },
          {
            "or": [
              {
                "and": [
                  {
                    "src": "",
                    "op": "==",
                    "dst": "bsc"
                  },
                  {
                    "src": "",
                    "op": "==",
                    "dst": "0x07da81e9a684ab87fad7206b3bc8d0866f48cc7c"
                  }
                ]
              },
              {
                "and": [
                  {
                    "src": "",
                    "op": "==",
                    "dst": "combo"
                  },
                  {
                    "src": "",
                    "op": "==",
                    "dst": "0xba7b9936a965fac23bb7a8190364fa60622b3cff"
                  }
                ]
              }
            ]
          },
          {
            "src": "",
            "op": ">=",
            "dst": "50000"
          }
        ]
      }
    ],
    "values": [
      true
    ],
    "endpoint": "http://localhost:9933"
  },
  "issuer": {
    "id": "did:litentry:substrate:0xda340fed8f85f3a3ee9dd2c7aa36c29c79ad87eb19b5d78544278d7605566caf",
    "name": "Litentry TEE Worker",
    "mrenclave": "8GkkAQ81Rc9TrRn6JWtUwEZD8DWF5k8DbLBxroX5Ln1N",
    "runtimeVersion": {
      "parachain": 9180,
      "sidechain": 106
    }
  },
  "issuanceDate": "2024-05-29T23:13:58.497467222+00:00",
  "parachainBlockNumber": 5,
  "sidechainBlockNumber": 2,
  "proof": {
    "created": "2024-05-29T23:13:58.497724076+00:00",
    "type": "Ed25519Signature2020",
    "proofPurpose": "assertionMethod",
    "proofValue": "c2dd8a1ead0b9655b8c69eb92d393b933c61ec1a7e1b2a41b6e2c8349578a7d9b0560995f51a71352743c5ff4d3451ba4389b2df84ae7cddbec374f0664fa20f",
    "verificationMethod": "0xda340fed8f85f3a3ee9dd2c7aa36c29c79ad87eb19b5d78544278d7605566caf"
  },
  "credentialSchema": {
    "id": "https://raw.githubusercontent.com/litentry/vc-jsonschema/main/dist/schemas/25-token-holding-amount/1-1-2.json",
    "type": "JsonSchemaValidator2018"
  }
}```

**Pull request merged**
