### PR TITLE
update rustc version to 1.74.0 in create-release-draft

### PR DESCRIPTION
**Pull request by BillyWooo**
very minor PR: upgrade rustc version to 1.74.0 in create-release-draft. 
Wrong branch name.

### CODE REVIEW

**Comment by Kailai-Wang** [comment]
Please change `build-wasm.yml` too (and try to build the runtime with it)

**Comment by Kailai-Wang** [comment]
One sec - I might have a branch that I was working on to fix it already:
https://github.com/litentry/litentry-parachain/compare/dev...cleanup-srtool-wasm

**Comment by Kailai-Wang** [comment]
This one: https://github.com/litentry/litentry-parachain/pull/3034

**Comment by BillyWooo** [comment]
#3034

**Pull request closed without merging**
