### PR TITLE
ts-test automatically generates type-definitions

### LINKED ISSUE #1345: ts-test automatically generates type-definitions
reference to https://polkadot.js.org/docs/api/start/types.extend

### PR DESCRIPTION
**Pull request by 0xverin**
resolves #1345 

Usage:

1. `yarn load-meta` get metadata;

2. `yarn generate` generates type-definitions

Note:
1. I downgraded the version of polkadot/api because ^10.x was not working. Check out [this issue ](https://github.com/polkadot-js/api/issues/5540)for more information. we won't be able to increase the polkadot/api version until the issue is resolved.
2. All types can be generated automatically. Considering that there are quite a few changes to make when using these types in ts-test, I think creating an issue and another PR to handle this is necessary.

### CODE REVIEW

**Review by arieljbirnbaum — APPROVED** [review]

**Comment by Kailai-Wang** [comment]
Does [this comment](https://github.com/polkadot-js/api/issues/5582#issuecomment-1497344626) say anything to you? And [this comment](https://github.com/polkadot-js/api/issues/5524#issuecomment-1472343946)?

Can we use `^10.1.3` maybe?

cc @grumpygreenguy @higherordertech

**Comment by higherordertech** [comment]
will try 10.1.3 and raise seperate PR

**Comment by higherordertech** [comment]
> will try 10.1.3 and raise seperate PR

will try 10.1.3 and raise seperate PR

**Comment by wli-pro** [comment]
> Does [this comment](https://github.com/polkadot-js/api/issues/5582#issuecomment-1497344626) say anything to you? And [this comment](https://github.com/polkadot-js/api/issues/5524#issuecomment-1472343946)?
> 
> Can we use `^10.1.3` maybe?
> 
> cc @grumpygreenguy @higherordertech

I will try 10.1.3 and raise seperate PR

**Comment by wli-pro** [comment]
Hey @Kailai-Wang  @grumpygreenguy @Verin1005  The version is upgraded in this PR: https://github.com/litentry/litentry-parachain/pull/1660 and is working.

**Pull request merged**
