### PR TITLE
optimize cli commands

### PR DESCRIPTION
**Pull request by Marky-Shi**
#946  optimize cli commands

### CODE REVIEW

**Comment by Kailai-Wang** [comment]
Thank you, can you please adjust Dockerfile as well? Like [here](https://github.com/litentry/litentry-parachain/compare/dev...943-add-onfinality-script#diff-f34da55ca08f1a30591d8b0b3e885bcc678537b2a9a4aadea4f190806b374ddc)

**Comment by Marky-Shi** [comment]
> Thank you, can you please adjust Dockerfile as well? Like [here](https://github.com/litentry/litentry-parachain/compare/dev...943-add-onfinality-script#diff-f34da55ca08f1a30591d8b0b3e885bcc678537b2a9a4aadea4f190806b374ddc)

No problem, I'll deal with it right away

**Review by Kailai-Wang — APPROVED** [review]
Looks good!

**Comment by Kailai-Wang** [comment]
btw please use the [auto-close keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) to auto close the linked issue :)

and delete the branch if not needed

**Pull request merged**
