### PR TITLE
sync upstream integritee pallets code 

### LINKED ISSUE #1157: Sync upstream integritee-pallets code
### Context
Sync upstream integritee-pallets code && test  [generate_teerex_upstream_patch.sh](https://github.com/litentry/litentry-parachain/blob/dev/scripts/generate_teerex_upstream_patch.sh)

### PR DESCRIPTION
**Pull request by Marky-Shi**
resloves #1157 
sync upstream integritee-pallets && test  [generate_teerex_upstream_patch.sh](https://github.com/litentry/litentry-parachain/blob/issue-1157/scripts/generate_teerex_upstream_patch.sh).

There is no big problem with this script execution, you need to be careful when resolving conflicts, and don't forget to remove `upstream.patch` at the end .

### CODE REVIEW

**Comment by BillyWooo** [comment]
can you add "upstream.patch" to gitignore?

**Comment by Kailai-Wang** [comment]
> don't forget to remove upstream.patch at the end

I don't think you should remove it, instead it should be put under `pallets/` and add a comment to explain what this is about.

**Comment by Marky-Shi** [comment]
> > don't forget to remove upstream.patch at the end
> 
> I don't think you should remove it, instead it should be put under `pallets/` and add a comment to explain what this is about.

okay  got it

**Review by jingleizhang — APPROVED** [review]
let's move it under `pallets/`

**Comment by BillyWooo** [comment]
> > don't forget to remove upstream.patch at the end
> 
> I don't think you should remove it, instead it should be put under `pallets/` and add a comment to explain what this is about.

This is the generated patch file. Not the commit hash code. Why should we keep it?

**Comment by Kailai-Wang** [comment]
> > > don't forget to remove upstream.patch at the end
> > 
> > 
> > I don't think you should remove it, instead it should be put under `pallets/` and add a comment to explain what this is about.
> 
> This is the generated patch file. Not the commit hash code. Why should we keep it?

I meant `upstream_commit` sorry (that's why I mentioned we should put it under `pallets/`)

**Comment by BillyWooo** [comment]
Please go ahead, just ignore `move file upstream_commit into pallet/`. I am working on restructuring these updating scripts. Will have another PR ASAP.

**Comment by Marky-Shi** [comment]
> > > > don't forget to remove upstream.patch at the end
> > > 
> > > 
> > > I don't think you should remove it, instead it should be put under `pallets/` and add a comment to explain what this is about.
> > 
> > 
> > This is the generated patch file. Not the commit hash code. Why should we keep it?
> 
> I meant `upstream_commit` sorry (that's why I mentioned we should put it under `pallets/`)

@Kailai-Wang  @BillyWooo  How about such a modification?  My personal opinion is that pallets/READE.md should preferably include content that is updated each time the upstream code is synchronized. 
For  example :  
commit: xxxxxxx(hash code)
update:

- xxxx
- xxxx
- xxxx
- and so on.  

Perhaps we can change README.md to sync_upstream.md or change.md.
BTW, I modified the path where upstream_commit is stored in the  `generate_teerex_upstream_patch.sh` script.

**Review by jingleizhang — APPROVED** [review]
Looks good:

- added explanations to pallets/README.md
- moved upstream_commit under pallets

**Pull request merged**
