### PR TITLE
Always init GLOBAL_SCHEDULED_ENCLAVE

### PR DESCRIPTION
**Pull request by kziemianek**
* initializes `GLOBAL_SCHEDULED_ENCLAVE` for any worker type, previously it was initialized only in case of sidechain worker.

### CODE REVIEW

**Review by BillyWooo — APPROVED** [review]
LGTM

**Review by felixfaisal — APPROVED** [review]
LGTM

**Review by Kailai-Wang — APPROVED** [review]
While I have no objection to the PR itself, I'm wondering if we actually need/use `GLOBAL_SCHEDULED_ENCLAVE` in bc-worker, except for `state_getMrenclave`.

We shouldn't care about the scheduled_enclave in bc-worker, the validity of mrenclave will be checked upon enclave registration 🤔 

If `state_getMrenclave` is the only reference, maybe we should use other ways to retrieve mrenclave in the rpc handler

**Comment by kziemianek** [comment]
> While I have no objection to the PR itself, I'm wondering if we actually need/use `GLOBAL_SCHEDULED_ENCLAVE` in bc-worker, except for `state_getMrenclave`.
> 
> We shouldn't care about the scheduled_enclave in bc-worker, the validity of mrenclave will be checked upon enclave registration 🤔
> 
> If `state_getMrenclave` is the only reference, maybe we should use other ways to retrieve mrenclave in the rpc handler

You are right, it was [raised](https://github.com/litentry/litentry-parachain/pull/2452#discussion_r1475670688) before. 
I'll remove all related code to scheduled enclave to avoid ambiguity.

**Pull request closed without merging**
