### PR TITLE
Vc verification

### LINKED ISSUE #1260: ts-test should get shard from parachain instead of local worker node
related PR is https://github.com/litentry/litentry-parachain/pull/1222

image

### LINKED ISSUE #1306: VC verification in ts-tests
### Context

#1238 

this version:
- [x] assertion values
- [x] signature
- [x] issuer attestation
- [x] vc registry status

### PR DESCRIPTION
**Pull request by 0xverin**
resolves #1306

### CODE REVIEW

**Comment by 0xverin** [comment]
btw solved #1260

**Comment by Kailai-Wang** [comment]
> btw solved #1260

it needs to be manually linked :)

**Comment by 0xverin** [comment]
just support #1369

**Comment by zTgx** [comment]
merged to https://github.com/litentry/litentry-parachain/pull/1369, close it.

**Pull request closed without merging**
