### PR TITLE
Fix truncated chain spec in parachain-launch

### LINKED ISSUE #2099: Fix truncated chain spec in parachain-launch
### Context

Follow-up of #2081

#2098 is still a workaround, see the PR description.

We'll still need a way to solve it cleanly

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

### PR DESCRIPTION
**Pull request by Traf333**
this PR tends to remove workaround (#2098)  in order to keep things simple and consistent without supporting forked packages

Fixes: #2099

### CODE REVIEW

**Comment by Traf333** [comment]
In addition, I've triggered whole system build to be sure the CI will work in case we touch some rust code
https://github.com/litentry/litentry-parachain/actions/runs/7330479550

**Comment by Kailai-Wang** [comment]
Could you explain a bit why this PR fixes the issue? I don't get it 😂

**Comment by Traf333** [comment]
> Could you explain a bit why this PR fixes the issue? I don't get it 😂

As from description I understood that we got some tests failing in CI and we introduced workaround https://github.com/litentry/litentry-parachain/pull/2098 

Maybe I understood the issue in a wrong way 🤔  

if it's not the case, can you help me to understand what's the expected result? @Kailai-Wang

**Comment by Kailai-Wang** [comment]
> As from description I understood that we got some tests failing in CI and we introduced workaround #2098 

This is correct, but simply reverting this PR won't solve the problem :(

The issue is aimed to find the root cause and really "fix" it instead of working around it

**Comment by Traf333** [comment]
This PR includes not only reverting your PR, but
- updated some packages
- preventing build for the `@open-web3/parachain-launch` which might cause the issue

and I was thinking if the tests are green - it means the issue is solved 😄 
since I reverted the workaround, probably now we should be able to see the issue, right? do you know how can I reproduce it?

**Comment by Kailai-Wang** [comment]
> do you know how can I reproduce it?

This is the hardest part, the issue was a race condition that (I believe) was related to the I/O buffering. While it worked most of the time, it did fail sometimes.

You could read the links (to upstream PRs/issues, which are linked again to other issues) in the original PR thoroughly.

We can also revert it (but then maybe you want a higher version of the package) and see how it goes, but that's not a legit "fix" :)

**Comment by 0xverin** [comment]
>do you know how can I reproduce it?

As we briefly discussed in the meeting, this part is challenging to reproduce, which is also why I mentioned "not sure." :p

**Comment by Traf333** [comment]
> but then maybe you want a higher version of the package

Not sure there are any major changes which might be related to our case, even packages update are only touched dev packages
https://github.com/open-web3-stack/parachain-launch/compare/v1.4.2...v2.0.0

Thanks for the input. 🙏  I'll re-read related issue and PR carefully and will continue to debug

**Comment by Kailai-Wang** [comment]
Thanks!

Feel free to jump on any other tasks that have a higher priority tho :)

**Comment by Traf333** [comment]
closing it for now as it stale and may pick up later

**Pull request closed without merging**
