### PR TITLE
fix: P-654 added solana signature check

### PR DESCRIPTION
**Pull request by wli-pro**
### Context

as titles

### Labels

Please apply following PR-related labels when appropriate:
- `C0-breaking`: if your change could break the existing client, e.g. API change, critical logic change 
- `C1-noteworthy`: if your change is non-breaking, but is still worth noticing for the client, e.g. reference code improvement

### Testing Evidences

Please attach any relevant evidences if applicable

Tested via unit test

### CODE REVIEW

**Review by silva-fj — COMMENTED** [review]
Do we have a place where we put shared/common code between workers? if not, what's the reason?

**Comment by BillyWooo** [comment]
> Do we have a place where we put shared/common code between workers? if not, what's the reason?

This is under discussion. Check issue P-600 and related ones.

**Comment by BillyWooo** [comment]
The changes looks good to me. Can you take a look at the CI test failure of one worker?

**Review by Kailai-Wang — COMMENTED** [review]
Shall we have ts-test for it (at least happy path)?

**Comment by wli-pro** [comment]
> Shall we have ts-test for it (at least happy path)?

Yes integration tests have been added too.

**Comment by Kailai-Wang** [comment]
> > Shall we have ts-test for it (at least happy path)?
> 
> Yes integration tests have been added too.

I'm not sure if the test is run in CI though

**Review by Kailai-Wang — APPROVED** [review]
Thanks!

**Pull request merged**
