### PR TITLE
Return encoded extrinsics without padding

### LINKED ISSUE #2168: Worker always fails to recognize itself as primary validateer
After a startup the worker registers itself in teerex's enclave registry and tries to determine whether he's a primary validateer (the first to be registered) or not but from my experience it looks like it always says it's not.

I've checked the campaign instances logs and it seems the problem existed there too.

```
[2023-09-27T21:26:23Z ERROR litentry_worker] ExtrinsicFailed ExtrinsicNotFound
[<] Extrinsic got finalized. Hash: None
```

In short, the implementation could not determine the block at which extrinsic was finalized so it fallbacks to current block. Then based on current block it check if any registered enclave existed before. The answer is yes, thus it pretends as it's not the primary while in fact it is.

```
if we_are_primary_validateer {
	println!("[+] We are the primary validateer");
} else {
	println!("[+] We are NOT the primary validateer");
}
```

Upstream ticket: https://github.com/scs/substrate-api-client/issues/624

### PR DESCRIPTION
**Pull request by Kailai-Wang**
### Context

It should fix the `ExtrinsicNotFound` error during enclave registration.

With the padded version (post-padded with spaces `0x20`) the extrinsic submission would succeed since the decoding goes through even with postpositioned (unused) bytes. However, the substrate-api-client wouldn't find the hash with the prolonged extrinsic that we pass in. 

This is also the reason why CI of #2281 failed

fixes #2168 
fixes P-151

Related: https://github.com/scs/substrate-api-client/issues/624

### CODE REVIEW

**Comment by Kailai-Wang** [comment]
Reported upstream too: https://github.com/integritee-network/worker/pull/1505

**Comment by kziemianek** [comment]
@Kailai-Wang does it fix #2168 ?

**Comment by Kailai-Wang** [comment]
> @Kailai-Wang does it fix #2168 ?

It should.

However, (I was about to say to you) the registration process needs to be reviewed after this one and #2281 get merged: https://github.com/litentry/litentry-parachain/issues/1133

**Review by BillyWooo — APPROVED** [review]
Thank you for the explanation. I think it's good to go.

**Pull request merged**
