### PR TITLE
Rename `G_DATA_PROVIDERS` to `GLOBAL_DATA_PROVIDER`

### PR DESCRIPTION
**Pull request by Kailai-Wang**
### Context

A trivial PR for renaming:
- to be consistent with other global variables
- `G_` is a bit confusing
- `DataProvidersStatic` => `DataProviderConfig`

This PR also updates the metadata and shortens the VC assertion list in ts-test, see comments:
```
// TODO: keep the list short, the manual types will be solved in #1878
//       more extensive testing of assertion will be done in #1873
```

### CODE REVIEW

**Review by kziemianek — COMMENTED** [review]
What do you think about naming it `GLOBAL_CONFIG_PROVIDER` ?

**Comment by kziemianek** [comment]
Data providers are:

- Achainable
- Discord
- Twitter

`DataProvidersStatic` struct holds only configuration for mentioned above providers.

**Comment by Kailai-Wang** [comment]
Then `GLOBAL_DATA_PROVIDER_CONFIG`? "data provider" is a term widely used in discussions, so I'd like to keep both words

Then `DataProvidersStatic` should be changed to `DataProviderStaticConfig` too?

**Comment by kziemianek** [comment]
> 

Sounds good. Maybe we can remove this `Static` word too so `DataProviderStaticConfig` -> `DataProviderConfig`. For me both versions are fine, I just prefer the latter.

**Comment by Kailai-Wang** [comment]
Sure - I added a bit more renaming :)

**Review by BillyWooo — APPROVED** [review]
LGTM. 
Also thanks @kziemianek for the suggestions.

**Review by kziemianek — APPROVED** [review]

**Pull request merged**
