### PR TITLE
More debug logs (fix #1301)

### LINKED ISSUE #1301: Add more debug logs
### Context
Sometimes CI still fails without knowing why, mostly timeout. E.g.

https://github.com/litentry/litentry-parachain/actions/runs/4131843340
https://github.com/litentry/litentry-parachain/actions/runs/4131681102

I think it helps if we can add more debug-level logs in tee to cover the lifecycle of litentry indirect calls - ideally we can see every timepoint of where it's handled

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

### PR DESCRIPTION
**Pull request by jingleizhang**
the issue is https://github.com/litentry/litentry-parachain/issues/1301

### CODE REVIEW

**Comment by Kailai-Wang** [comment]
`fix #1301` won't link the issue automatically if it's written in the title - we still need to use auto-close keyword :)

**Review by Kailai-Wang — COMMENTED** [review]
Thanks!

Shall we:
- add more logs in the block importer/indirect-call-executor/top-pool? Ideally we can track a life-cycle of an indirect call, like create_identity, we need to know when exactly it's found in the parentchain block, when it's added to the top pool, when it's processed, when it's removed from the top pool, when it's executed ...
- turn on the logs in CI
- remove spammy logs of little use, like:
```
[2023-03-03T12:39:36Z WARN  sp_io::storage] storage::start_transaction unimplemented
[2023-03-03T12:39:36Z WARN  sp_io::storage] storage::commit_transaction unimplemented
```

**Comment by jingleizhang** [comment]
- [x] add more logs in the block importer/indirect-call-executor/top-pool
- [x] turn on the logs in CI
- [x] remove spammy logs of little use, in` sp_io::storage`

**Comment by jingleizhang** [comment]
- [x] updated RUST_LOG in `tee-worker/docker/docker-compose.yml` and `tee-worker/local-setup/py/worker.py`

**Review by Kailai-Wang — COMMENTED** [review]
Thanks.

I see the logs in CI look much better now, however, I still didn't find the debug logs in the STF-execution (this is very crucial for debugging):
```
[2023-03-06T16:27:00Z DEBUG itc_parentchain_indirect_calls_executor] Scanning block 41 for relevant xt
[2023-03-06T16:27:00Z DEBUG itc_parentchain_indirect_calls_executor::executor] found extrinsic(call index: [64, 3]) with status true
[2023-03-06T16:27:00Z DEBUG itc_parentchain_indirect_calls_executor::executor::litentry::create_identity] execute indirect call: CreateIdentity, who: "8eaf04151687736326c9fea17e25fc5287613693c912909cb226aa4794f26a48", identity: Substrate { network: Litentry, address: Address32([142, 175, 4, 21, 22, 135, 115, 99, 38, 201, 254, 161, 126, 37, 252, 82, 135, 97, 54, 147, 201, 18, 144, 156, 178, 38, 170, 71, 148, 242, 106, 72]) }
[2023-03-06T16:27:00Z DEBUG integritee_service::ocall_bridge::bridge_api] Requesting RemoteAttestation OCall API instance
[2023-03-06T16:27:00Z DEBUG integritee_service::ocall_bridge::ffi::init_quote] Entering ocall_sgx_init_quote
[2023-03-06T16:27:00Z DEBUG integritee_service::ocall_bridge::remote_attestation_ocall] RemoteAttestationBridge: init quote
[2023-03-06T16:27:00Z DEBUG enclave_runtime::ocall::attestation_ocall] [Enclave] Report creation successful. mr_signer.m = [131, 215, 25, 231, 125, 234, 202, 20, 112, 246, 186, 246, 42, 77, 119, 67, 3, 200, 153, 219, 105, 2, 15, 156, 112, 238, 29, 252, 8, 199, 206, 158]
[2023-03-06T16:27:00Z DEBUG ita_stf::stf_sgx] Account fb930b3745d624b34c06391d3ab1c10418afc689bde83325dbbd6140a25609db nonce is 5
[2023-03-06T16:27:00Z DEBUG itp_top_pool_author::api] [Pool] creating hash of indirect_call(TrustedCallSigned { call: create_identity_runtime(, , Substrate { network: Litentry, address: Address32([142, 175, 4, 21, 22, 135, 115, 99, 38, 201, 254, 161, 126, 37, 252, 82, 135, 97, 54, 147, 201, 18, 144, 156, 178, 38, 170, 71, 148, 242, 106, 72]) }, None, 41), nonce: 5, signature: <wasm:stripped> })
[2023-03-06T16:27:00Z DEBUG itp_top_pool_author::author] Submitting trusted call to TOP pool: create_identity_runtime(, , Substrate { network: Litentry, address: Address32([142, 175, 4, 21, 22, 135, 115, 99, 38, 201, 254, 161, 126, 37, 252, 82, 135, 97, 54, 147, 201, 18, 144, 156, 178, 38, 170, 71, 148, 242, 106, 72]) }, None, 41), TOP hash: 0xb9a891da70a94b9acf1d3669f24296a9aab0b1e63c8d8441dec249494996d035
[2023-03-06T16:27:00Z DEBUG itp_top_pool_author::api] [Pool] creating hash of indirect_call(TrustedCallSigned { call: create_identity_runtime(, , Substrate { network: Litentry, address: Address32([142, 175, 4, 21, 22, 135, 115, 99, 38, 201, 254, 161, 126, 37, 252, 82, 135, 97, 54, 147, 201, 18, 144, 156, 178, 38, 170, 71, 148, 242, 106, 72]) }, None, 41), nonce: 5, signature: <wasm:stripped> })
[2023-03-06T16:27:00Z INFO  itc_parentchain_block_importer::block_importer] Successfully imported parentchain block (number: 41, hash: 0xb3ae…4f48)
[2023-03-06T16:27:00Z DEBUG integritee_service::ocall_bridge::bridge_api] Requesting WorkerOnChain OCall API instance
[2023-03-06T16:27:00Z DEBUG integritee_service::ocall_bridge::worker_on_chain_ocall] Enclave wants to send 1 extrinsics
[2023-03-06T16:27:00Z DEBUG integritee_service::ocall_bridge::worker_on_chain_ocall] Send extrinsic, call length: 350
```

this is the snippet.
I can see the logs are present in the trusted_call executors, maybe we only need to activate it.

**Comment by jingleizhang** [comment]
done. There might be missing a comma in RUST_LOG.

**Review by Kailai-Wang — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
