### PR TITLE
bitacross client sample golang code

### PR DESCRIPTION
**Pull request by kziemianek**
Sample golang code for requesting `SignEthereum` direct call from bitacross worker.

### CODE REVIEW

**Review by felixfaisal — APPROVED** [review]
LGTM
I was wondering if we should also verify the signature received with the public key, to make sure there are no shenanigans in the decoding

**Comment by kziemianek** [comment]
> LGTM I was wondering if we should also verify the signature received with the public key, to make sure there are no shenanigans in the decoding

This can be done later once bitacross worker exposes rpc method for retrieving public keys. In general I think it's not necessary to have such check in this example.

**Comment by Kailai-Wang** [comment]
A naive question: have you tried it on the actual bc-worker host (or connect to it)?

**Comment by kziemianek** [comment]
> A naive question: have you tried it on the actual bc-worker host (or connect to it)?

No I've only tested it against bc-worker run on my host.

**Pull request merged**
