### PR TITLE
Adjust the assertion codec index

### PR DESCRIPTION
**Pull request by BillyWooo**
very minor change as title. 
But I think it's worth it.

### CODE REVIEW

**Review by Kailai-Wang — APPROVED** [review]
It's fine as long as we haven't started to use it yet and nothing occupied 21 before

cc @jonalvarezz too

**Comment by Kailai-Wang** [comment]
Btw it's still safer to adjust `vc/definitions.ts` too, although I don't know if @Verin1005 is using it or not (if not, why not delete them?)

**Comment by BillyWooo** [comment]
> Btw it's still safer to adjust `vc/definitions.ts` too, although I don't know if @Verin1005 is using it or not (if not, why not delete them?)

This order is adjusted with 'vc/definitions.ts` already.

**Comment by Kailai-Wang** [comment]
> > Btw it's still safer to adjust `vc/definitions.ts` too, although I don't know if @Verin1005 is using it or not (if not, why not delete them?)
> 
> This order is adjusted with 'vc/definitions.ts` already.

This is even worse :D as it means we made some mistakes ...

**Review by jonalvarezz — APPROVED** [review]
IDH uses indirect calls, so the impact is low and constraint to type changes only.

**Comment by Kailai-Wang** [comment]
> IDH uses indirect calls, so the impact is low and constraint to type changes only.

IDH uses direct vc request (which requires `assertion` parameter), doesn't it

This PR is on dev branch anyway so it's targeted at DI definitely

I'll still mark it as "breaking" and merge it

**Pull request merged**
