### PR TITLE
[WIP] Upgrade polkdot v1.11.0

### PR DESCRIPTION
**Pull request by wli-pro**
### Context

P-1110 upgrade polkdot to enable async backing

### Labels

Please apply following PR-related labels when appropriate:
- `C0-breaking`: if your change could break the existing client, e.g. API change, critical logic change 
- `C1-noteworthy`: if your change is non-breaking, but is still worth noticing for the client, e.g. reference code improvement

### Testing Evidences

Please attach any relevant evidences if applicable

### CODE REVIEW

**Comment by wli-pro** [comment]
https://linear.app/litentry/issue/P-1110/investigate-and-apply-async-backing

**Comment by Kailai-Wang** [comment]
What's the status of this PR? Any estimation when it can be merged? 🙌

**Comment by BillyWooo** [comment]
> What's the status of this PR? Any estimation when it can be merged? 🙌

Currently it's blocked by "found duplicate lang item `panic_impl`" from sp-io. Still investigating the implicit feature dependency conflict. 
Estimation: maybe one or two more days. Not clear about further coming errors yet.

**Comment by Kailai-Wang** [comment]
Let's finish the dep upgrade ASAP, and then investigate the async backing support (if it's not enabled by default)

**Comment by BillyWooo** [comment]
new PR #3190

**Pull request closed without merging**
