### PR TITLE
update teerex test cases

### PR DESCRIPTION
**Pull request by zTgx**
relevant pr:

https://github.com/litentry/litentry-parachain/pull/1222

### CODE REVIEW

**Comment by BillyWooo** [comment]
Why weren't these test cases triggered in #1222 CI ?

**Comment by Kailai-Wang** [comment]
Good catch, thanks 👍 

Yea I have the same question. This probably implies we have some flaws in CI commands

**Comment by Kailai-Wang** [comment]
I think it's because we only run the tests with `skip-ias-feature`, but not without. 
Upstream tests all cases: https://github.com/litentry/integritee-pallets/blob/2d7ab45d74194d4fbf529adf9fb4e2758f681cdb/.github/workflows/ci.yml#L33-L42

Btw I tried to run it without this feature, one testcase failed:
```
failures:

---- tests::test_cases::confirm_processed_parentchain_block_works stdout ----
thread 'tests::test_cases::confirm_processed_parentchain_block_works' panicked at 'assertion failed: `(left != right)`
  left: `1587900450000`,
 right: `1587900450000`', pallets/teerex/src/tests/test_cases.rs:710:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    tests::test_cases::confirm_processed_parentchain_block_works
```

**Comment by zTgx** [comment]
> I think it's because we only run the tests with `skip-ias-feature`, but not without. Upstream tests all cases: https://github.com/litentry/integritee-pallets/blob/2d7ab45d74194d4fbf529adf9fb4e2758f681cdb/.github/workflows/ci.yml#L33-L42
> 
> Btw I tried to run it without this feature, one testcase failed:
> 
> ```
> failures:
> 
> ---- tests::test_cases::confirm_processed_parentchain_block_works stdout ----
> thread 'tests::test_cases::confirm_processed_parentchain_block_works' panicked at 'assertion failed: `(left != right)`
>   left: `1587900450000`,
>  right: `1587900450000`', pallets/teerex/src/tests/test_cases.rs:710:9
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 
> 
> failures:
>     tests::test_cases::confirm_processed_parentchain_block_works
> ```


We can submit another pr to fix all testcases without `skip-ias-feaure` .

**Comment by DogLi** [comment]
> I think it's because we only run the tests with `skip-ias-feature`, but not without. Upstream tests all cases: https://github.com/litentry/integritee-pallets/blob/2d7ab45d74194d4fbf529adf9fb4e2758f681cdb/.github/workflows/ci.yml#L33-L42
> 
> Btw I tried to run it without this feature, one testcase failed:
> 
> ```
> failures:
> 
> ---- tests::test_cases::confirm_processed_parentchain_block_works stdout ----
> thread 'tests::test_cases::confirm_processed_parentchain_block_works' panicked at 'assertion failed: `(left != right)`
>   left: `1587900450000`,
>  right: `1587900450000`', pallets/teerex/src/tests/test_cases.rs:710:9
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 
> 
> failures:
>     tests::test_cases::confirm_processed_parentchain_block_works
> ```

what's the difference between the `left` and `right`?  `1587900450000 == 1587900450000`

**Comment by Kailai-Wang** [comment]
> > I think it's because we only run the tests with `skip-ias-feature`, but not without. Upstream tests all cases: https://github.com/litentry/integritee-pallets/blob/2d7ab45d74194d4fbf529adf9fb4e2758f681cdb/.github/workflows/ci.yml#L33-L42
> > Btw I tried to run it without this feature, one testcase failed:
> > ```
> > failures:
> > 
> > ---- tests::test_cases::confirm_processed_parentchain_block_works stdout ----
> > thread 'tests::test_cases::confirm_processed_parentchain_block_works' panicked at 'assertion failed: `(left != right)`
> >   left: `1587900450000`,
> >  right: `1587900450000`', pallets/teerex/src/tests/test_cases.rs:710:9
> > note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> > 
> > 
> > failures:
> >     tests::test_cases::confirm_processed_parentchain_block_works
> > ```
> 
> what's the difference between the `left` and `right`? `1587900450000 == 1587900450000`

We assert they are non-equal.

**Review by jingleizhang — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
