### PR TITLE
fix: P-1203 unified npm package version

### PR DESCRIPTION
**Pull request by wli-pro**
### Context

Fixing conflicting npm package.

### Labels

Please apply following PR-related labels when appropriate:
- `C0-breaking`: if your change could break the existing client, e.g. API change, critical logic change 
- `C1-noteworthy`: if your change is non-breaking, but is still worth noticing for the client, e.g. reference code improvement

### Testing Evidences

Please attach any relevant evidences if applicable

### CODE REVIEW

**Comment by Kailai-Wang** [comment]
@0xverin please review it : )

**Review by 0xverin — COMMENTED** [review]
1. After deleting `pnpm-lock.yaml` and `node_modules`, there are still many unmet peers when running pnpm install. I think the lock file should be deleted(at least at this update) and then update the package for testing, otherwise, it's impossible to know the correct version range of the package, as the locked version is used during pnpm install.
image


2. ts-tests still have unmet peers (tested without deleting pnpm-lock.yaml).
image

3. Can you find a way to run all the tests in CI (like adding a console.log in tests to triggle ci or something), the CI passed, but actually none of the tests were run?I am worried that with version modifications, some methods may become ineffective. thank you.

**Comment by wli-pro** [comment]
> 1. After deleting `pnpm-lock.yaml` and `node_modules`, there are still many unmet peers when running pnpm install. I think the lock file should be deleted(at least at this update) and then update the package for testing, otherwise, it's impossible to know the correct version range of the package, as the locked version is used during pnpm install.
> 
> image
> 2. ts-tests still have unmet peers (tested without deleting pnpm-lock.yaml).
> 
> image
> 3. Can you find a way to run all the tests in CI (like adding a console.log in tests to triggle ci or something), the CI passed, but actually none of the tests were run?I am worried that with version modifications, some methods may become ineffective. thank you.

fixed now.

**Comment by 0xverin** [comment]
> > 1. After deleting `pnpm-lock.yaml` and `node_modules`, there are still many unmet peers when running pnpm install. I think the lock file should be deleted(at least at this update) and then update the package for testing, otherwise, it's impossible to know the correct version range of the package, as the locked version is used during pnpm install.
> > 
> > image
> > 2. ts-tests still have unmet peers (tested without deleting pnpm-lock.yaml).
> > image
> > 3. Can you find a way to run all the tests in CI (like adding a console.log in tests to triggle ci or something), the CI passed, but actually none of the tests were run?I am worried that with version modifications, some methods may become ineffective. thank you.
> 
> fixed now.

I also fixed the issues after the solc upgrade In parachain ts-tests.

**Review by 0xverin — APPROVED** [review]

**Pull request merged**
