### PR TITLE
Improve the nonce handling in STF execution

### LINKED ISSUE #1175: Occasional  STF execution failure: InvalidNonce(2)
### Context

Occasionally CI failed because some STFs weren't executed successfully, e.g. [this run](https://github.com/litentry/litentry-parachain/actions/runs/3881542642/attempts/1) - I re-attach the logs.

The demo log shows that after the transfer the balance is unchanged: 

```
Get balance of Alice's incognito account
9000000000000

Get balance of Bob's incognito account
0

* Send 2000000000000 funds from Alice's incognito account to Bob's incognito account
send trusted call transfer from 5Dt1Wg85pXGLstt36t6TDdvXXoCtG6zkUL17KkyVaPYSrzGH to 5CtBzV6DZQUqhtiq3XAMPgYkcAfrbSuxPjjz4PAs98tuzSVB: 2000000000000

* Get balance of Alice's incognito account
9000000000000
```

In worker log there's something like
```
[2023-01-10T10:50:48Z ERROR itp_stf_executor::executor] Stf execute failed: InvalidNonce(2)
```

Questions are:
- why did the transfer fail?
- is it a timing problem? maybe waiting for 30sec is not enough? But it can't explain why it happened upstream too: https://github.com/integritee-network/worker/actions/runs/3882003200/jobs/6622681953, where the block interval is 6s
- was the `InvalidNonce` error the cause or result of the previous failure? I could imagine that if an STF fails to execute, the system nonce won't be incremented, but the nonce is the trusted-call is already pre-calculated when signing => hence the mismatch

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.
[logs-M6-sidechain.zip](https://github.com/litentry/litentry-parachain/files/10384401/logs-M6-sidechain.zip)

### PR DESCRIPTION
**Pull request by Kailai-Wang**
resolves #1175 

This PR tries to improve the nonce handling and tests in the following aspects:
- take the pending tx into consideration when retrieving nonces from CLI (this only affects tests for now)
- increment the nonce regardless of the stf execution status
- solidify the tests by waiting for the state with a timeout

### CODE REVIEW

**Comment by Kailai-Wang** [comment]
Strange that the tests passed locally (I tried a few times) but failed in CI: https://github.com/litentry/litentry-parachain/actions/runs/3957044710

In logs I see:
```
[2023-01-19T11:40:00Z ERROR integritee_service::ocall_bridge::worker_on_chain_ocall] Could not send extrsinic to node: RpcClient(Extrinsic("Unexpected extrinsic status: Future, stopped watch process prematurely."))
```

But it's an error when sending extrinsic to the parachain, not sure if it's related.

**Comment by Kailai-Wang** [comment]
Re-run solved it.

My change should have no impact on the communication towards the parachain, so I assume it's unrelated. Buf we should keep an eye on it if it happens again/more often

**Review by BillyWooo — APPROVED** [review]
Thanks. LGTM

**Review by ziming-zung — APPROVED** [review]
Looks good

**Pull request merged**
