### PR TITLE
p-939 Add balances moving script

### PR DESCRIPTION
**Pull request by 0xverin**
### Context

steps:
1. `corepack pnpm install`
2. `pnpm exec ts-node batch-transfer.ts`

Will get 2 json files:
- one stores data of system account:`system-accounts-entries-litmus-2024-08-12.json`
[system-accounts-entries-litmus-2024-08-13.json](https://github.com/user-attachments/files/16600442/system-accounts-entries-litmus-2024-08-13.json)
- one stores extrinsics hexdata: `extrinsics-2024-08-12.json`
[extrinsics-2024-08-13.json](https://github.com/user-attachments/files/16600444/extrinsics-2024-08-13.json)

Test evidence:
The hex encoded extrinsics can be recognized by litentry network.
image

preimage hash:
image

### CODE REVIEW

**Comment by Kailai-Wang** [comment]
Please output the preimage hash too - we need it to submit a democracy proposal

**Comment by 0xverin** [comment]
> Please output the preimage hash too - we need it to submit a democracy proposal

Done! Pls check description.

**Comment by 0xverin** [comment]
[system-accounts-entries-litmus-2024-08-13.json](https://github.com/user-attachments/files/16600442/system-accounts-entries-litmus-2024-08-13.json)
[extrinsics-2024-08-13.json](https://github.com/user-attachments/files/16600444/extrinsics-2024-08-13.json)

**Comment by Kailai-Wang** [comment]
Thank you!

I didn't realise there would be 28 batches - I think that's too verbose for root operations (= 28 refs) :( 

Maybe this would work too:
- we have a referendum to mint X tokens to a specific account, X is the sum of the all accounts' balances from the JSON (which should be equal to `balances.totalIssuance()` too) + sufficient transaction fees 
- we use batched balance transfer to add the balances to all affected accounts

@wangminqi does it sound good to you?
@0xverin can you please generate batch balance transfer hex? Please use `utility.forceBatch` and let's try to use 1000 batch size

In this way we only need 1 ref but ofc you have to trust the receipt account operator

**Comment by 0xverin** [comment]
[extrinsics-2024-08-19.json](https://github.com/user-attachments/files/16667536/extrinsics-2024-08-19.json)
[system-accounts-entries-litmus-2024-08-19.json](https://github.com/user-attachments/files/16667537/system-accounts-entries-litmus-2024-08-19.json)

**Comment by 0xverin** [comment]
> Thank you!
> 
> I didn't realise there would be 28 batches - I think that's too verbose for root operations (= 28 refs) :(
> 
> Maybe this would work too:
> 
> * we have a referendum to mint X tokens to a specific account, X is the sum of the all accounts' balances from the JSON (which should be equal to `balances.totalIssuance()` too) + sufficient transaction fees
> * we use batched balance transfer to add the balances to all affected accounts
> 
> @wangminqi does it sound good to you? @0xverin can you please generate batch balance transfer hex? Please use `utility.forceBatch` and let's try to use 1000 batch size
> 
> In this way we only need 1 ref but ofc you have to trust the receipt account operator

Done.
[extrinsics-2024-08-19.json](https://github.com/user-attachments/files/16667539/extrinsics-2024-08-19.json)
[system-accounts-entries-litmus-2024-08-19.json](https://github.com/user-attachments/files/16667540/system-accounts-entries-litmus-2024-08-19.json)

**Comment by 0xverin** [comment]
adding totalissuance:
[extrinsics-2024-08-23.json](https://github.com/user-attachments/files/16720887/extrinsics-2024-08-23.json)

**Review by Kailai-Wang — APPROVED** [review]
Thanks

**Comment by Kailai-Wang** [comment]
**Update:**

this was the snapshot:

[system-accounts-entries-litmus-2024-09-03.json](https://github.com/user-attachments/files/17394335/system-accounts-entries-litmus-2024-09-03.json)

encoded extrinsics:

[extrinsics-2024-09-03.json](https://github.com/user-attachments/files/17394334/extrinsics-2024-09-03.json)

**Pull request merged**
