### PR TITLE
Handling missing branch for Email identity in match patterns

### PR DESCRIPTION
**Pull request by silva-fj**

### CODE REVIEW

**Comment by silva-fj** [comment]
FYI this release branch was already broken, some changes related to `Assertion`s:

https://github.com/litentry/litentry-parachain/actions/runs/10826722348/job/30038362291

I don't know what is missing, I have not checked the commit history

**Comment by Kailai-Wang** [comment]
I think the error reported it clearly:
```
#12 381.1 error[E0004]: non-exhaustive patterns: `&Assertion::LinkedIdentities` not covered
#12 381.1    --> /home/ubuntu/tee-worker/litentry/core/credentials/src/credential_schema.rs:27:8
#12 381.1     |
#12 381.1 27  |     match assertion {
#12 381.1     |           ^^^^^^^^^ pattern `&Assertion::LinkedIdentities` not covered
#12 381.1     |
#12 381.1 note: `Assertion` defined here
#12 381.1    --> /home/ubuntu/primitives/core/src/assertion/mod.rs:146:2
#12 381.1     |
#12 381.1 65  | pub enum Assertion {
#12 381.1     | ------------------
#12 381.1 ...
#12 381.1 146 |     LinkedIdentities,
#12 381.1     |     ^^^^^^^^^^^^^^^^ not covered
#12 381.1     = note: the matched value is of type `&Assertion`
#12 381.1 help: ensure that all possible cases are being handled by adding a match arm with a wildcard pattern or an explicit pattern as shown

```

**Comment by silva-fj** [comment]
> I think the error reported it clearly:
> 
> ```
> #12 381.1 error[E0004]: non-exhaustive patterns: `&Assertion::LinkedIdentities` not covered
> #12 381.1    --> /home/ubuntu/tee-worker/litentry/core/credentials/src/credential_schema.rs:27:8
> #12 381.1     |
> #12 381.1 27  |     match assertion {
> #12 381.1     |           ^^^^^^^^^ pattern `&Assertion::LinkedIdentities` not covered
> #12 381.1     |
> #12 381.1 note: `Assertion` defined here
> #12 381.1    --> /home/ubuntu/primitives/core/src/assertion/mod.rs:146:2
> #12 381.1     |
> #12 381.1 65  | pub enum Assertion {
> #12 381.1     | ------------------
> #12 381.1 ...
> #12 381.1 146 |     LinkedIdentities,
> #12 381.1     |     ^^^^^^^^^^^^^^^^ not covered
> #12 381.1     = note: the matched value is of type `&Assertion`
> #12 381.1 help: ensure that all possible cases are being handled by adding a match arm with a wildcard pattern or an explicit pattern as shown
> ```

Yep, what I meant is that I don't know the full context of these changes. In dev branch this variant is also not covered so I assume this is some work in progress (I don't know what the value for that schema should be)

**Comment by Kailai-Wang** [comment]
I think @higherordertech updated the release branch due to the same reason that you have - he wanted to update the primitives to include another entry (but probably only the enum itself, not the places where it's referenced, hence the error)

**Comment by BillyWooo** [comment]
The error is clear. But strange, why this https://github.com/litentry/litentry-parachain/pull/3042 passed.

**Comment by wli-pro** [comment]
> I think @higherordertech updated the release branch due to the same reason that you have - he wanted to update the primitives to include another entry (but probably only the enum itself, not the places where it's referenced, hence the error)









Fixed now
image

**Pull request merged**
