### PR TITLE
Adjust start parameters for integration test

### LINKED ISSUE #81: Adjust start parameters for integration test
Currently our CI test starts two relaychain nodes (alice and bob) and two parachain collators (litentry-collator):

args for collator 0:
`--collator --tmp --parachain-id 1984 --port 40333 --ws-port 9844 --alice --execution native -- --execution wasm --chain ./rococo-local-cfde-real-overseer.json --port 30343 --ws-port 9977`

args for collator 1:
`--collator --tmp --parachain-id 1984 --port 40334 --ws-port 9845 --alice -- --execution native --chain ./rococo-local-cfde-real-overseer.json --port 30344 --ws-port 9978`

IMHO this is suboptimal:

- We would only need 1 collator, as this CI mainly focuses on the functionality of the parachain, not the consensus between parachains. Furthermore, [substrate recommends n + 1 validators with n parachains](https://github.com/substrate-developer-hub/substrate-parachain-template#start-relay-chain). 

   In our case two collators had to be started as otherwise no blocks could be generated because of single-node-network for parachains. However this can be overcome via `force-authoring`.

- execution strategy seems to make less sense. According to https://substrate.dev/docs/en/knowledgebase/advanced/executor, I'd prefer to either use default, or both wasm.

### PR DESCRIPTION
**Pull request by Kailai-Wang**
See issue #81, Small adjustment of parachain startup parameters for our integration test

- only start one collator instance
- always use wasm executor for both collator and embedded relaychain node

### CODE REVIEW

**Review by Satoshi-Kusumoto — COMMENTED** [review]
Why request a review for Draft

**Comment by Kailai-Wang** [comment]
> Why request a review for Draft

see the linked issue, zongxiong was making changes to the codes simutaneously and I reverted this PR from "ready" to "WIP".
The "blocked by" relationship was also set in zenHub, I'll adjust it and re-request it later when it's resumed.

**Comment by chenzongxiong** [comment]
Please rebase the `dev` branch before PR. I merged PR #70   into our dev branch

**Review by chenzongxiong — CHANGES_REQUESTED** [review]
Rebase it and add `--force-authoring`

**Review by chenzongxiong — APPROVED** [review]

**Review by chenzongxiong — APPROVED** [review]

**Review by Satoshi-Kusumoto — APPROVED** [review]
I think this PR (issue) is trivial. Anyway after we introduce collator staking, this has to be changed. I just think, since there are still a lot of other tasks, we may not spend much time on these optimizations first

**Pull request merged**
