### PR TITLE
Vesting-Proxy-Multisig-Identity [CODE REVIEW ONLY]

### PR DESCRIPTION
**Pull request by BillyWooo**

### CODE REVIEW

**Comment by Kailai-Wang** [comment]
It's hard to review with all changes accumulated.
Can you please use p-895 as target branch?

**Comment by wangminqi** [comment]
> It's hard to review with all changes accumulated. Can you please use p-895 as target branch?

https://github.com/litentry/litentry-parachain/pull/2942/files
Use this branch which target 895 and comment there.
This should equally work.
This branch is just for triggering CI.

**Comment by wangminqi** [comment]
LGTM.
This branch has been merged into P-895.
This branch will no longer be maintained. Everything moved to 895.

**Comment by Kailai-Wang** [comment]
I see, thanks.

> This branch is just for triggering CI.

It's mentioned multiple times that manually triggering CI is a better option in this case 🙌

**Pull request closed without merging**
