### PR TITLE
debug: simpler parameter_types

### LINKED ISSUE #615: Replace parameter_types constants with const trait
### Context
see e.g. https://github.com/paritytech/substrate/pull/11254
Using `Constxx<>` can reduce the verbosity when binding constant parameter types.

### Task
Replace the parameter_types constants with the new trait, e.g. `OperationalFeeMultiplier` 
But please consider the readability and maintainability too, e.g. don't hardcode the constant when a constant is used across multiple files or things like `pub const a: u8 = 0`.

### Acceptance criteria
parameter_types constants are replaced.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

### PR DESCRIPTION
**Pull request by wangminqi**
This closes #615

### CODE REVIEW

**Comment by Kailai-Wang** [comment]
Thanks @wangminqi, generally looks good to me.

I think we're fine to refactor all the `Max...` constants, however, I'm thinking of keeping the following variable as unchanged, what do you think?
- SS58Prefix (we are probably going to move it to some privimits/constants)
- MinimumPeriod
- PreimageMaxSize
those are calculated via arithmetic operations and subject to future changes

**Comment by wangminqi** [comment]
I will keep all mock/test to constU form and recover all parachain code referred above back.

> Thanks @wangminqi, generally looks good to me.
> 
> I think we're fine to refactor all the `Max...` constants, however, I'm thinking of keeping the following variable as unchanged, what do you think?
> 
> * SS58Prefix (we are probably going to move it to some privimits/constants)
> * MinimumPeriod
> * PreimageMaxSize
>   those are calculated via arithmetic operations and subject to future changes

**Comment by wangminqi** [comment]
I feel SS58Prefix should be meaningful to recover back.
MinimumPeriod is relied on SLOT_DURATION, which is already a constant. I feel no need. 
PreimageMaxSize, I am neutral to its recover. Just feel it is a "constant" number that is between worth/not worthy in the constant mod.

**Comment by Kailai-Wang** [comment]
> I feel SS58Prefix should be meaningful to recover back. MinimumPeriod is relied on SLOT_DURATION, which is already a constant. I feel no need. PreimageMaxSize, I am neutral to its recover. Just feel it is a "constant" number that is between worth/not worthy in the constant mod.

Cool, let's just revert `SS58Prefix` and `PreimageMaxSize`

**Review by Kailai-Wang — APPROVED** [review]

**Pull request merged**
