### PR TITLE
Refactor ClassOfYear name type to enum

### PR DESCRIPTION
**Pull request by outofxxx**
This PR only deals with the `ClassOfYear` Achainable type alone, if there are no issues, the subsequent PR will change the type of the Name field from `string` to `enum` for the remaining Achainable types.

**Also, this is a breaking change.**

### CODE REVIEW

**Comment by jonalvarezz** [comment]
Hi @zhouhuitian , can you elaborate on how clients are impacted so we can follow up and update client-sdk correspondingly?

**Comment by Kailai-Wang** [comment]
> Hi @zhouhuitian , can you elaborate on how clients are impacted so we can follow up and update client-sdk correspondingly?

I guess it's the type change for `name` - it uses enum instead of string now.
It will affect how the client constructs the vc request.

**Comment by outofxxx** [comment]
> Hi @zhouhuitian , can you elaborate on how clients are impacted so we can follow up and update client-sdk correspondingly?


Yes, after this modification, when constructing the request, the "name" field no longer needs to be entered as characters; you can only select from the provided enum options.

**Review by 0xverin — COMMENTED** [review]
overall looks good, I only checked type-definitions

**Review by jonalvarezz — APPROVED** [review]

**Comment by jonalvarezz** [comment]
fyi: I created this sub-ticket to track the client-sdk change https://linear.app/litentry/issue/P-649/client-sdk-update-achainable-class-of-year-request-payload

**Comment by BillyWooo** [comment]
Maybe let's hold on this topic for a moment.

**Comment by Kailai-Wang** [comment]
Shall we continue this PR?

**Comment by kziemianek** [comment]
> Shall we continue this PR?

This PR is open since February, what's the decision?

**Comment by BillyWooo** [comment]
Close it for the moment:
1. We will take over Achainable service.
2. We will move to Solidity solution.

**Pull request closed without merging**
