### PR TITLE
clone only filtered tops

### PR DESCRIPTION
**Pull request by kziemianek**
I found this during working on other tasks. It simply reduces the amount of TOPs cloned during retrieval from top pool.

### CODE REVIEW

**Review by Kailai-Wang — COMMENTED** [review]
Now that we are super close, would you like to use `filter_map` to chain them? :D

**Comment by kziemianek** [comment]
> Now that we are super close, would you like to use `filter_map` to chain them? :D

I think I prefer 

```
			.filter(|o| matches!(o.data(), TrustedOperation::get(Getter::trusted(_))))
			.map(|o| o.data().clone())
```

over 

```
			.filter_map(|o| {
				if matches!(o.data(), TrustedOperation::get(Getter::trusted(_))) {
					Some(o.data().clone())
				} else {
					None
				}
			})
```

What do you think @Kailai-Wang ?

**Comment by Kailai-Wang** [comment]
I actually reckon this has a better readability:
```
.filter_map(|o| match o.data() {
  TrustedOperation::get(Getter::trusted(_)) => Some(o.data().clone()),
  _ => None
})
.collect()
```
But yea it's rather a flavor's problem

**Review by Kailai-Wang — APPROVED** [review]
Either way I'll approve it

**Pull request merged**
