### PR TITLE
fix duplicate logs in ts-tests output

### LINKED ISSUE #1757: Duplicate logs in the ts-test output
### Context

For better debugging in ts-test we tried to print the events in each block when we subscribe to the new parachain header. However, we seem to have duplicated outputs (3x) for one record, which spams the whole log.

e.g.
```
Event[0]: treasury.UpdatedInactive [8350124363,8478865223]
Event[1]: system.ExtrinsicSuccess [{"weight":{"refTime":292490000,"proofSize":3867},"class":"Mandatory","paysFee":"Yes"}]
Event[2]: system.ExtrinsicSuccess [{"weight":{"refTime":99840000,"proofSize":0},"class":"Mandatory","paysFee":"No"}]
Event[3]: balances.Withdraw ["5HA9ns8MxcQ3NY9W4gH85ciBBwWbCvwgQQg3NQ2JmSapHb2V",321851791]
Event[4]: teerex.ProcessedParentchainBlock ["5HA9ns8MxcQ3NY9W4gH85ciBBwWbCvwgQQg3NQ2JmSapHb2V","0xbd89c49533d1b1b74280b6c8e275695b335cf684088ea58f423d0a0a2bbd270d","0x0000000000000000000000000000000000000000000000000000000000000000",32]
Event[5]: balances.Deposit ["5EYCAe5ijiYfyeZ2JJCGq56LmPyNRAKzpG4QkoQkkQNB5e6Z",128740716]
Event[6]: treasury.Deposit [128740716]
Event[7]: transactionPayment.TransactionFeePaid ["5HA9ns8MxcQ3NY9W4gH85ciBBwWbCvwgQQg3NQ2JmSapHb2V",321851791,0]
Event[8]: system.ExtrinsicSuccess [{"weight":{"refTime":147864000,"proofSize":0},"class":"Normal","paysFee":"Yes"}]
Event[0]: treasury.UpdatedInactive [8350124363,8478865223]
Event[1]: system.ExtrinsicSuccess [{"weight":{"refTime":292490000,"proofSize":3867},"class":"Mandatory","paysFee":"Yes"}]
Event[2]: system.ExtrinsicSuccess [{"weight":{"refTime":99840000,"proofSize":0},"class":"Mandatory","paysFee":"No"}]
Event[3]: balances.Withdraw ["5HA9ns8MxcQ3NY9W4gH85ciBBwWbCvwgQQg3NQ2JmSapHb2V",321851791]
Event[4]: teerex.ProcessedParentchainBlock ["5HA9ns8MxcQ3NY9W4gH85ciBBwWbCvwgQQg3NQ2JmSapHb2V","0xbd89c49533d1b1b74280b6c8e275695b335cf684088ea58f423d0a0a2bbd270d","0x0000000000000000000000000000000000000000000000000000000000000000",32]
Event[5]: balances.Deposit ["5EYCAe5ijiYfyeZ2JJCGq56LmPyNRAKzpG4QkoQkkQNB5e6Z",128740716]
Event[6]: treasury.Deposit [128740716]
Event[7]: transactionPayment.TransactionFeePaid ["5HA9ns8MxcQ3NY9W4gH85ciBBwWbCvwgQQg3NQ2JmSapHb2V",321851791,0]
Event[8]: system.ExtrinsicSuccess [{"weight":{"refTime":147864000,"proofSize":0},"class":"Normal","paysFee":"Yes"}]
Event[0]: treasury.UpdatedInactive [8350124363,8478865223]
Event[1]: system.ExtrinsicSuccess [{"weight":{"refTime":292490000,"proofSize":3867},"class":"Mandatory","paysFee":"Yes"}]
Event[2]: system.ExtrinsicSuccess [{"weight":{"refTime":99840000,"proofSize":0},"class":"Mandatory","paysFee":"No"}]
Event[3]: balances.Withdraw ["5HA9ns8MxcQ3NY9W4gH85ciBBwWbCvwgQQg3NQ2JmSapHb2V",321851791]
Event[4]: teerex.ProcessedParentchainBlock ["5HA9ns8MxcQ3NY9W4gH85ciBBwWbCvwgQQg3NQ2JmSapHb2V","0xbd89c49533d1b1b74280b6c8e275695b335cf684088ea58f423d0a0a2bbd270d","0x0000000000000000000000000000000000000000000000000000000000000000",32]
Event[5]: balances.Deposit ["5EYCAe5ijiYfyeZ2JJCGq56LmPyNRAKzpG4QkoQkkQNB5e6Z",128740716]
Event[6]: treasury.Deposit [128740716]
Event[7]: transactionPayment.TransactionFeePaid ["5HA9ns8MxcQ3NY9W4gH85ciBBwWbCvwgQQg3NQ2JmSapHb2V",321851791,0]
Event[8]: system.ExtrinsicSuccess [{"weight":{"refTime":147864000,"proofSize":0},"class":"Normal","paysFee":"Yes"}]
```
Have we done anything wrong in our code?

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

### PR DESCRIPTION
**Pull request by 0xverin**
## Summary
resolves #1757 
Two [foreach loops](https://github.com/litentry/litentry-parachain/blob/dev/tee-worker/ts-tests/common/transactions.ts#L106) caused duplicate printing of the logs, and it has now been fixed.

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing client application to not work as expected)
- [ ] Documentation update
- [ ] Examples (adding tests)

### CODE REVIEW

**Comment by 0xverin** [comment]
This is a screenshot of the modified test, there is no longer any duplicate printing between the two events. They are now displayed in sequential order.
image

**Comment by Kailai-Wang** [comment]
~~Thank you! As far as I understand the code, it only tries to de-duplicate the logs. Do you know why the logs appear multiple times in the first place?~~

Nvm, I just saw your PR description

Can't we move `records.forEach((e, i) => {` block out of the extrinsic iteration loop?
That `forEach` loop for records seems to do nothing more than the printing

**Comment by 0xverin** [comment]
> Can't we move `records.forEach((e, i) => {` block out of the extrinsic iteration loop? That `forEach` loop for records seems to do nothing more than the printing

Thank you for opening up my mind. This is indeed the correct solution.

**Comment by 0xverin** [comment]
Let me run a few rounds of `identity/bulk-identity` tests. I don't want to see the two CI errors that occurred earlier. I want to double-check them.

**Comment by 0xverin** [comment]
>Let me run a few rounds of identity/bulk-identity tests. I don't want to see the two CI errors that occurred earlier. I want to double-check them.

Ready for review.

**Review by Kailai-Wang — APPROVED** [review]
Looks good

**Pull request merged**
